// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Foo.proto

package test.dlmu.protoc.test;

public final class Foo {
  private Foo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FooRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string indata = 1;
    /**
     * <code>required string indata = 1;</code>
     */
    boolean hasIndata();
    /**
     * <code>required string indata = 1;</code>
     */
    java.lang.String getIndata();
    /**
     * <code>required string indata = 1;</code>
     */
    com.google.protobuf.ByteString
        getIndataBytes();
  }
  /**
   * Protobuf type {@code FooRequest}
   */
  public static final class FooRequest extends
      com.google.protobuf.GeneratedMessage
      implements FooRequestOrBuilder {
    // Use FooRequest.newBuilder() to construct.
    private FooRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FooRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FooRequest defaultInstance;
    public static FooRequest getDefaultInstance() {
      return defaultInstance;
    }

    public FooRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FooRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              indata_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.dlmu.protoc.test.Foo.internal_static_FooRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.dlmu.protoc.test.Foo.internal_static_FooRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.dlmu.protoc.test.Foo.FooRequest.class, test.dlmu.protoc.test.Foo.FooRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<FooRequest> PARSER =
        new com.google.protobuf.AbstractParser<FooRequest>() {
      public FooRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FooRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FooRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string indata = 1;
    public static final int INDATA_FIELD_NUMBER = 1;
    private java.lang.Object indata_;
    /**
     * <code>required string indata = 1;</code>
     */
    public boolean hasIndata() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string indata = 1;</code>
     */
    public java.lang.String getIndata() {
      java.lang.Object ref = indata_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          indata_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string indata = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIndataBytes() {
      java.lang.Object ref = indata_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        indata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      indata_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIndata()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIndataBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIndataBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.dlmu.protoc.test.Foo.FooRequest)) {
        return super.equals(obj);
      }
      test.dlmu.protoc.test.Foo.FooRequest other = (test.dlmu.protoc.test.Foo.FooRequest) obj;

      boolean result = true;
      result = result && (hasIndata() == other.hasIndata());
      if (hasIndata()) {
        result = result && getIndata()
            .equals(other.getIndata());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasIndata()) {
        hash = (37 * hash) + INDATA_FIELD_NUMBER;
        hash = (53 * hash) + getIndata().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.dlmu.protoc.test.Foo.FooRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.dlmu.protoc.test.Foo.FooRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.dlmu.protoc.test.Foo.FooRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.dlmu.protoc.test.Foo.FooRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.dlmu.protoc.test.Foo.FooRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static test.dlmu.protoc.test.Foo.FooRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static test.dlmu.protoc.test.Foo.FooRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static test.dlmu.protoc.test.Foo.FooRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static test.dlmu.protoc.test.Foo.FooRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static test.dlmu.protoc.test.Foo.FooRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(test.dlmu.protoc.test.Foo.FooRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FooRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements test.dlmu.protoc.test.Foo.FooRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.dlmu.protoc.test.Foo.internal_static_FooRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.dlmu.protoc.test.Foo.internal_static_FooRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.dlmu.protoc.test.Foo.FooRequest.class, test.dlmu.protoc.test.Foo.FooRequest.Builder.class);
      }

      // Construct using test.dlmu.protoc.test.Foo.FooRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        indata_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.dlmu.protoc.test.Foo.internal_static_FooRequest_descriptor;
      }

      public test.dlmu.protoc.test.Foo.FooRequest getDefaultInstanceForType() {
        return test.dlmu.protoc.test.Foo.FooRequest.getDefaultInstance();
      }

      public test.dlmu.protoc.test.Foo.FooRequest build() {
        test.dlmu.protoc.test.Foo.FooRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public test.dlmu.protoc.test.Foo.FooRequest buildPartial() {
        test.dlmu.protoc.test.Foo.FooRequest result = new test.dlmu.protoc.test.Foo.FooRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.indata_ = indata_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.dlmu.protoc.test.Foo.FooRequest) {
          return mergeFrom((test.dlmu.protoc.test.Foo.FooRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.dlmu.protoc.test.Foo.FooRequest other) {
        if (other == test.dlmu.protoc.test.Foo.FooRequest.getDefaultInstance()) return this;
        if (other.hasIndata()) {
          bitField0_ |= 0x00000001;
          indata_ = other.indata_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIndata()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.dlmu.protoc.test.Foo.FooRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.dlmu.protoc.test.Foo.FooRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string indata = 1;
      private java.lang.Object indata_ = "";
      /**
       * <code>required string indata = 1;</code>
       */
      public boolean hasIndata() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string indata = 1;</code>
       */
      public java.lang.String getIndata() {
        java.lang.Object ref = indata_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          indata_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string indata = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIndataBytes() {
        java.lang.Object ref = indata_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          indata_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string indata = 1;</code>
       */
      public Builder setIndata(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        indata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string indata = 1;</code>
       */
      public Builder clearIndata() {
        bitField0_ = (bitField0_ & ~0x00000001);
        indata_ = getDefaultInstance().getIndata();
        onChanged();
        return this;
      }
      /**
       * <code>required string indata = 1;</code>
       */
      public Builder setIndataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        indata_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FooRequest)
    }

    static {
      defaultInstance = new FooRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FooRequest)
  }

  public interface FooResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string outdata = 1;
    /**
     * <code>required string outdata = 1;</code>
     */
    boolean hasOutdata();
    /**
     * <code>required string outdata = 1;</code>
     */
    java.lang.String getOutdata();
    /**
     * <code>required string outdata = 1;</code>
     */
    com.google.protobuf.ByteString
        getOutdataBytes();
  }
  /**
   * Protobuf type {@code FooResponse}
   */
  public static final class FooResponse extends
      com.google.protobuf.GeneratedMessage
      implements FooResponseOrBuilder {
    // Use FooResponse.newBuilder() to construct.
    private FooResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FooResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FooResponse defaultInstance;
    public static FooResponse getDefaultInstance() {
      return defaultInstance;
    }

    public FooResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FooResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              outdata_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.dlmu.protoc.test.Foo.internal_static_FooResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.dlmu.protoc.test.Foo.internal_static_FooResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.dlmu.protoc.test.Foo.FooResponse.class, test.dlmu.protoc.test.Foo.FooResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<FooResponse> PARSER =
        new com.google.protobuf.AbstractParser<FooResponse>() {
      public FooResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FooResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FooResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string outdata = 1;
    public static final int OUTDATA_FIELD_NUMBER = 1;
    private java.lang.Object outdata_;
    /**
     * <code>required string outdata = 1;</code>
     */
    public boolean hasOutdata() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string outdata = 1;</code>
     */
    public java.lang.String getOutdata() {
      java.lang.Object ref = outdata_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          outdata_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string outdata = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOutdataBytes() {
      java.lang.Object ref = outdata_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outdata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      outdata_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasOutdata()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getOutdataBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getOutdataBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.dlmu.protoc.test.Foo.FooResponse)) {
        return super.equals(obj);
      }
      test.dlmu.protoc.test.Foo.FooResponse other = (test.dlmu.protoc.test.Foo.FooResponse) obj;

      boolean result = true;
      result = result && (hasOutdata() == other.hasOutdata());
      if (hasOutdata()) {
        result = result && getOutdata()
            .equals(other.getOutdata());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasOutdata()) {
        hash = (37 * hash) + OUTDATA_FIELD_NUMBER;
        hash = (53 * hash) + getOutdata().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.dlmu.protoc.test.Foo.FooResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.dlmu.protoc.test.Foo.FooResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.dlmu.protoc.test.Foo.FooResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.dlmu.protoc.test.Foo.FooResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.dlmu.protoc.test.Foo.FooResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static test.dlmu.protoc.test.Foo.FooResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static test.dlmu.protoc.test.Foo.FooResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static test.dlmu.protoc.test.Foo.FooResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static test.dlmu.protoc.test.Foo.FooResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static test.dlmu.protoc.test.Foo.FooResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(test.dlmu.protoc.test.Foo.FooResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FooResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements test.dlmu.protoc.test.Foo.FooResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.dlmu.protoc.test.Foo.internal_static_FooResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.dlmu.protoc.test.Foo.internal_static_FooResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.dlmu.protoc.test.Foo.FooResponse.class, test.dlmu.protoc.test.Foo.FooResponse.Builder.class);
      }

      // Construct using test.dlmu.protoc.test.Foo.FooResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        outdata_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.dlmu.protoc.test.Foo.internal_static_FooResponse_descriptor;
      }

      public test.dlmu.protoc.test.Foo.FooResponse getDefaultInstanceForType() {
        return test.dlmu.protoc.test.Foo.FooResponse.getDefaultInstance();
      }

      public test.dlmu.protoc.test.Foo.FooResponse build() {
        test.dlmu.protoc.test.Foo.FooResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public test.dlmu.protoc.test.Foo.FooResponse buildPartial() {
        test.dlmu.protoc.test.Foo.FooResponse result = new test.dlmu.protoc.test.Foo.FooResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.outdata_ = outdata_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.dlmu.protoc.test.Foo.FooResponse) {
          return mergeFrom((test.dlmu.protoc.test.Foo.FooResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.dlmu.protoc.test.Foo.FooResponse other) {
        if (other == test.dlmu.protoc.test.Foo.FooResponse.getDefaultInstance()) return this;
        if (other.hasOutdata()) {
          bitField0_ |= 0x00000001;
          outdata_ = other.outdata_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOutdata()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.dlmu.protoc.test.Foo.FooResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.dlmu.protoc.test.Foo.FooResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string outdata = 1;
      private java.lang.Object outdata_ = "";
      /**
       * <code>required string outdata = 1;</code>
       */
      public boolean hasOutdata() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string outdata = 1;</code>
       */
      public java.lang.String getOutdata() {
        java.lang.Object ref = outdata_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          outdata_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string outdata = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOutdataBytes() {
        java.lang.Object ref = outdata_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          outdata_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string outdata = 1;</code>
       */
      public Builder setOutdata(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        outdata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string outdata = 1;</code>
       */
      public Builder clearOutdata() {
        bitField0_ = (bitField0_ & ~0x00000001);
        outdata_ = getDefaultInstance().getOutdata();
        onChanged();
        return this;
      }
      /**
       * <code>required string outdata = 1;</code>
       */
      public Builder setOutdataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        outdata_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FooResponse)
    }

    static {
      defaultInstance = new FooResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FooResponse)
  }

  /**
   * Protobuf service {@code FooService}
   */
  public static abstract class FooService
      implements com.google.protobuf.Service {
    protected FooService() {}

    public interface Interface {
      /**
       * <code>rpc Bar(.FooRequest) returns (.FooResponse);</code>
       */
      public abstract void bar(
          com.google.protobuf.RpcController controller,
          test.dlmu.protoc.test.Foo.FooRequest request,
          com.google.protobuf.RpcCallback<test.dlmu.protoc.test.Foo.FooResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new FooService() {
        @java.lang.Override
        public  void bar(
            com.google.protobuf.RpcController controller,
            test.dlmu.protoc.test.Foo.FooRequest request,
            com.google.protobuf.RpcCallback<test.dlmu.protoc.test.Foo.FooResponse> done) {
          impl.bar(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.bar(controller, (test.dlmu.protoc.test.Foo.FooRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return test.dlmu.protoc.test.Foo.FooRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return test.dlmu.protoc.test.Foo.FooResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc Bar(.FooRequest) returns (.FooResponse);</code>
     */
    public abstract void bar(
        com.google.protobuf.RpcController controller,
        test.dlmu.protoc.test.Foo.FooRequest request,
        com.google.protobuf.RpcCallback<test.dlmu.protoc.test.Foo.FooResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return test.dlmu.protoc.test.Foo.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.bar(controller, (test.dlmu.protoc.test.Foo.FooRequest)request,
            com.google.protobuf.RpcUtil.<test.dlmu.protoc.test.Foo.FooResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return test.dlmu.protoc.test.Foo.FooRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return test.dlmu.protoc.test.Foo.FooResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends test.dlmu.protoc.test.Foo.FooService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void bar(
          com.google.protobuf.RpcController controller,
          test.dlmu.protoc.test.Foo.FooRequest request,
          com.google.protobuf.RpcCallback<test.dlmu.protoc.test.Foo.FooResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          test.dlmu.protoc.test.Foo.FooResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            test.dlmu.protoc.test.Foo.FooResponse.class,
            test.dlmu.protoc.test.Foo.FooResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public test.dlmu.protoc.test.Foo.FooResponse bar(
          com.google.protobuf.RpcController controller,
          test.dlmu.protoc.test.Foo.FooRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public test.dlmu.protoc.test.Foo.FooResponse bar(
          com.google.protobuf.RpcController controller,
          test.dlmu.protoc.test.Foo.FooRequest request)
          throws com.google.protobuf.ServiceException {
        return (test.dlmu.protoc.test.Foo.FooResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          test.dlmu.protoc.test.Foo.FooResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:FooService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FooRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FooRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FooResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FooResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tFoo.proto\"\034\n\nFooRequest\022\016\n\006indata\030\001 \002(" +
      "\t\"\036\n\013FooResponse\022\017\n\007outdata\030\001 \002(\t2.\n\nFoo" +
      "Service\022 \n\003Bar\022\013.FooRequest\032\014.FooRespons" +
      "eB\"\n\025test.dlmu.protoc.testB\003Foo\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_FooRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_FooRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FooRequest_descriptor,
              new java.lang.String[] { "Indata", });
          internal_static_FooResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_FooResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FooResponse_descriptor,
              new java.lang.String[] { "Outdata", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
